---
# http://docs.ansible.com/ansible/latest/list_of_all_modules.html
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "nas_username"
      prompt: "Enter username for NAS"
      default: "aristarkh"
    - name: "nas_password"
      prompt: "Enter password for NAS"
      private: yes
  roles:
    - software
    - iptables
    - automount
    - nano
    - vim
    - grub
    - { role: backlight, when: ansible_form_factor == "Notebook" }

