---
nas_fqdn: "{{ nas_name }}.{{ nas_domain }}"
secret_file: "{{ ansible_user_dir }}/.{{ nas_name }}"
mount_directory: "/storage"
autofs_dir: "{{ '/etc' if ansible_pkg_mgr == 'apt' else
                '/etc/autofs' if ansible_pkg_mgr == 'pacman'}}"
