---
- name: Enable savedefault
  become: yes
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^[# ]*GRUB_SAVEDEFAULT=.*$'
    line: 'GRUB_SAVEDEFAULT="true"'
  notify: Update grub config

- name: Set grub_default=saved
  become: yes
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^[# ]*GRUB_DEFAULT=.*$'
    line: 'GRUB_DEFAULT="saved"'
  notify: Update grub config
